robospect:

# MOBILE PLATFORM
  
  # steering
  left_rear_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: left_rear_steering_joint
    pid: {p: 5000.0, i: 40.0, d: 10.0}
  
  # steering
  right_rear_steering_joint_controller:
    type: effort_controllers/JointPositionController
    joint: right_rear_steering_joint
    pid: {p: 5000.0, i: 40.0, d: 10.0}

  #traction
  left_front_axle_controller:
    #type: effort_controllers/JointEffortController
    type: effort_controllers/JointPositionController
    joint: left_front_axle_joint
    pid: {p: 7000.0, i: 5.0, d: 10.0}

  #traction
  right_front_axle_controller:
    #type: effort_controllers/JointEffortController
    type: effort_controllers/JointPositionController
    joint: right_front_axle_joint
    pid: {p: 7000.0, i: 5.0, d: 10.0}

  #traction
  left_rear_axle_controller:
    type: effort_controllers/JointPositionController
    joint: left_rear_axle_joint
    pid: {p: 7000.0, i: 5.0, d: 10.0}

  #traction
  right_rear_axle_controller:
    type: effort_controllers/JointPositionController
    joint: right_rear_axle_joint
    pid: {p: 7000.0, i: 5.0, d: 10.0}

# CRANE

  crane_first_joint_controller:
    type: effort_controllers/JointPositionController
    joint: crane_first_joint
    pid: {p: 5000.0, i: 5.0, d: 300.0}

  crane_second_joint_controller:
    type: effort_controllers/JointPositionController
    joint: crane_second_joint
    pid: {p: 20000.0, i: 1.0, d: 50.0}

  crane_third_joint_controller:
    type: effort_controllers/JointPositionController
    joint: crane_third_joint
    pid: {p: 30000.0, i: 5.0, d: 100.0}

  crane_fourth_joint_controller:
    type: effort_controllers/JointPositionController
    joint: crane_fourth_joint
    pid: {p: 5000.0, i: 5.0, d: 10.0}

  crane_fifth_joint_controller:
    type: effort_controllers/JointPositionController
    joint: crane_fifth_joint
    pid: {p: 40000.0, i: 5.0, d: 100.0}

  crane_sixth_joint_controller:
    type: effort_controllers/JointPositionController
    joint: crane_sixth_joint
    pid: {p: 30000.0, i: 5.0, d: 100.0}

  crane_seventh_joint_controller:
    type: effort_controllers/JointPositionController
    joint: crane_seventh_joint
    pid: {p: 15000.0, i: 5.0, d: 10.0}

  crane_tip_joint_controller:
    type: effort_controllers/JointPositionController
    joint: crane_tip_joint
    pid: {p: 10000.0, i: 5.0, d: 10.0}

  joint_read_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100.0
